[book]
authors = ["Chinmoy Gavini"]
language = "en"
multilingual = false
src = "src"
title = "Software Blog"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
additional-css = ["./theme/catppuccin.css"]
